/**
 * The colour moods a hymn background can be painted in. Every colour is light — the words sit
 * above the picture and the chapel's screens must stay bright — and tests check that no colour
 * here is ever dark.
 */

type Pair = [top: string, bottom: string];

export interface Palette {
  /** The title's colour on the title slide (deep, so it reads clearly; the art stays light). */
  ink: string;
  /** Warm glow of the light in the sky. */
  glow: string;
  sun: Pair;
  /** Land, from the farthest range to the foreground. */
  far: Pair;
  mid: Pair;
  near: Pair;
  ground: Pair;
  /** Water: top (near the horizon) and bottom, and the light on it. */
  water: Pair;
  shimmer: string;
  mist: string;
  cloud: Pair;
  /** Sunlight glazed onto the slopes that face the light. */
  glaze: string;
  foliage: string;
  trunk: string;
  /** Buildings and small things: walls, roofs, shadows, wood, the path. */
  walls: string;
  roof: string;
  shade: string;
  wood: string;
  path: string;
  flowers: [string, string, string, string];
}

const FLOWERS: Palette['flowers'] = ['#e6a8b6', '#f0d27e', '#fdfaf3', '#cdb9e2'];

export const PALETTES = {
  /** Misty blue mountains at sunrise (like How Great Thou Art). */
  dawn: {
    ink: '#24364f',
    glow: '#fdf0d6',
    sun: ['#fcebbe', '#f3cf84'],
    far: ['#c4cde0', '#eceff5'],
    mid: ['#a9b6d0', '#dde3ee'],
    near: ['#a3b9b8', '#d9e4e1'],
    ground: ['#b3c6c4', '#e1e9e6'],
    water: ['#dce6ef', '#b6c8da'],
    shimmer: '#f7fafc',
    mist: '#f7f3ea',
    cloud: ['#f6f7fa', '#ccd5e3'],
    glaze: '#fff6e4',
    foliage: '#8aa7a8',
    trunk: '#b8a690',
    walls: '#f5f0e8',
    roof: '#b9b3c4',
    shade: '#cfc9cf',
    wood: '#c2ae97',
    path: '#efe8da',
    flowers: FLOWERS,
  },
  /** Golden fields in morning sun (like Great Is Thy Faithfulness). */
  gold: {
    ink: '#4f3a1c',
    glow: '#f9df9f',
    sun: ['#fbe9b9', '#f3cf80'],
    far: ['#d8ddb2', '#eff1dc'],
    mid: ['#ebcd88', '#f7e9c6'],
    near: ['#e6c27c', '#f5e2b9'],
    ground: ['#e2be7c', '#f4e1b8'],
    water: ['#dde8e4', '#bdd2cd'],
    shimmer: '#fbf8ec',
    mist: '#fbf3e3',
    cloud: ['#fbf6ec', '#eedfc5'],
    glaze: '#fff4d6',
    foliage: '#b6c38c',
    trunk: '#b39a76',
    walls: '#f8f0e0',
    roof: '#d8ab8c',
    shade: '#dcc6a8',
    wood: '#caa77d',
    path: '#f4e8cc',
    flowers: ['#e9a9a0', '#f6e3a0', '#fdfaf3', '#d9c2a0'],
  },
  /** Rose-gold hills under glory (like To God Be the Glory). */
  rose: {
    ink: '#4a1d26',
    glow: '#fce6b0',
    sun: ['#fcecc6', '#f4cf90'],
    far: ['#efd2c4', '#f9ece4'],
    mid: ['#e2b2a3', '#f3dbd0'],
    near: ['#d79f92', '#efcdc2'],
    ground: ['#dba699', '#f1d4ca'],
    water: ['#efdedb', '#d9c3c2'],
    shimmer: '#fdf6ef',
    mist: '#fcf2e6',
    cloud: ['#fbeee4', '#f0d2c2'],
    glaze: '#fff0d8',
    foliage: '#c6b394',
    trunk: '#bea08c',
    walls: '#fbf2ea',
    roof: '#d7a49a',
    shade: '#e0c4bb',
    wood: '#c9a593',
    path: '#f6e6dc',
    flowers: ['#e8a2a8', '#f3d59a', '#fdf8f3', '#e2bfd4'],
  },
  /** Blue-grey mountains among high clouds (like Immortal, Invisible). */
  mist: {
    ink: '#2e3a4d',
    glow: '#fdf6e4',
    sun: ['#fdf1d6', '#f4d99c'],
    far: ['#c8d0df', '#ebeef4'],
    mid: ['#b7c2d7', '#e4e9f1'],
    near: ['#b7c2d5', '#e1e6ee'],
    ground: ['#b4c0d2', '#e0e5ed'],
    water: ['#e0e7ef', '#c2cfdf'],
    shimmer: '#f8fafc',
    mist: '#f7f5f0',
    cloud: ['#f6f7fa', '#c3cee0'],
    glaze: '#fff8e8',
    foliage: '#9eadc0',
    trunk: '#b4ab9f',
    walls: '#f5f3ef',
    roof: '#b8bccb',
    shade: '#cfd2da',
    wood: '#bfb2a2',
    path: '#eeebe4',
    flowers: ['#dcb8c6', '#efe0ad', '#fbfaf6', '#c9c4e2'],
  },
  /** Ancient sage-green hills and a stream (like O God, Our Help in Ages Past). */
  sage: {
    ink: '#2e4434',
    glow: '#fcefd4',
    sun: ['#fcedc6', '#f2d18e'],
    far: ['#d2d8c9', '#eef0e9'],
    mid: ['#b9c4b3', '#e1e6db'],
    near: ['#a8bba9', '#dbe4d8'],
    ground: ['#a9bca9', '#dce5d8'],
    water: ['#d6e5ec', '#b7cdd8'],
    shimmer: '#f4f8fa',
    mist: '#f7f2e8',
    cloud: ['#f2f2f0', '#d6d9da'],
    glaze: '#fff6e2',
    foliage: '#9fb39b',
    trunk: '#b3a28c',
    walls: '#f5f2ea',
    roof: '#bdb1a0',
    shade: '#cfcabd',
    wood: '#bea990',
    path: '#efeadc',
    flowers: FLOWERS,
  },
  /** Calm pale sea at sunrise (like Holy, Holy, Holy). */
  sea: {
    ink: '#1f3550',
    glow: '#f9e0aa',
    sun: ['#fcecc2', '#f4d08a'],
    far: ['#d3dbe6', '#e6ebf2'],
    mid: ['#c6d2e1', '#e3e9f1'],
    near: ['#b9c9da', '#dde6ef'],
    ground: ['#d9d6cc', '#efede6'],
    water: ['#dbe5ee', '#a3bad3'],
    shimmer: '#f6f9fb',
    mist: '#f6f3ec',
    cloud: ['#f6f8fa', '#cfd9e5'],
    glaze: '#fff2d8',
    foliage: '#a3b7b5',
    trunk: '#b9a993',
    walls: '#f6f3ee',
    roof: '#c2b4ab',
    shade: '#d3d0cd',
    wood: '#c4b29b',
    path: '#f0ebe0',
    flowers: FLOWERS,
  },
  /** Gold light over soft lavender hills (like Give to Our God Immortal Praise). */
  lavender: {
    ink: '#3d2a55',
    glow: '#f8dc9c',
    sun: ['#fbe6b6', '#f3d08c'],
    far: ['#dcd2e8', '#f2eef7'],
    mid: ['#c7b8dc', '#e8e1f1'],
    near: ['#b29fcf', '#e0d7ec'],
    ground: ['#b9a8d2', '#e4dcef'],
    water: ['#e3def0', '#c5bfdc'],
    shimmer: '#faf8fc',
    mist: '#faf4ec',
    cloud: ['#f7f4fa', '#ddd3ea'],
    glaze: '#fff2d6',
    foliage: '#aeabca',
    trunk: '#b7a7a6',
    walls: '#f7f3f6',
    roof: '#c4b0cf',
    shade: '#d8cfe0',
    wood: '#c3adaa',
    path: '#f1ebf2',
    flowers: ['#e6b0c4', '#f2dc9c', '#fdfbf7', '#cdbbe6'],
  },
  /** Green meadow in flower (like Praise, My Soul, the King of Heaven). */
  spring: {
    ink: '#2f4a2a',
    glow: '#fae6b0',
    sun: ['#fcebbe', '#f4d389'],
    far: ['#d3dec0', '#eef2e5'],
    mid: ['#bccf9f', '#e2ead2'],
    near: ['#a9c38c', '#dbe7cc'],
    ground: ['#a6c189', '#d9e6c9'],
    water: ['#d6e8ee', '#b6d3dd'],
    shimmer: '#f6fafb',
    mist: '#f6f5ea',
    cloud: ['#f7f8f4', '#d8e0d3'],
    glaze: '#fff5d8',
    foliage: '#9fbb83',
    trunk: '#b4a184',
    walls: '#f7f4ea',
    roof: '#c9a993',
    shade: '#d4d2bf',
    wood: '#c2aa88',
    path: '#f1ecda',
    flowers: FLOWERS,
  },
  /** Sea-green islands and clear water (like I Sing the Mighty Pow'r of God). */
  teal: {
    ink: '#1d4646',
    glow: '#f9e0a4',
    sun: ['#fcebbe', '#f3cf84'],
    far: ['#c3d7d3', '#e7efed'],
    mid: ['#abc7c2', '#d9e7e3'],
    near: ['#a2c2bb', '#d6e6e1'],
    ground: ['#d8d5c8', '#efede4'],
    water: ['#d3e5eb', '#a0c4d2'],
    shimmer: '#fafcfc',
    mist: '#f5f4ee',
    cloud: ['#f5f7f8', '#d7e0e5'],
    glaze: '#fff4dc',
    foliage: '#93b4ad',
    trunk: '#b6a790',
    walls: '#f6f4ee',
    roof: '#c7ad9e',
    shade: '#d2d3cc',
    wood: '#c1ae94',
    path: '#efebdf',
    flowers: FLOWERS,
  },
  /** Warm sand and palms of the Holy Land (like Hosanna, Loud Hosanna). */
  sand: {
    ink: '#4c3720',
    glow: '#f8e3b7',
    sun: ['#fcebc4', '#f4d494'],
    far: ['#e6d7b8', '#f4ede0'],
    mid: ['#dfcda8', '#f1e8d4'],
    near: ['#dccaa2', '#f1e8d4'],
    ground: ['#d9c49c', '#efe5ce'],
    water: ['#dae6e2', '#bdd2cd'],
    shimmer: '#fbf9f2',
    mist: '#fbf4e6',
    cloud: ['#fbf7ee', '#eadfca'],
    glaze: '#fff3d8',
    foliage: '#a5b577',
    trunk: '#bfa27d',
    walls: '#efe0c4',
    roof: '#d8bf98',
    shade: '#dcc49c',
    wood: '#c6a67e',
    path: '#f3ead6',
    flowers: ['#e7aab0', '#f2d88e', '#fdf9f1', '#d6bfd8'],
  },
  /** Soft apricot evening light. */
  peach: {
    ink: '#552c22',
    glow: '#fbe1b8',
    sun: ['#fde9c8', '#f6cf98'],
    far: ['#f1d9c6', '#faefe6'],
    mid: ['#ebc6ae', '#f6e3d6'],
    near: ['#e3b79d', '#f3dbcc'],
    ground: ['#e2b69c', '#f3dacb'],
    water: ['#efe0d8', '#dac6bf'],
    shimmer: '#fdf7f1',
    mist: '#fcf1e6',
    cloud: ['#fcf2e8', '#f0d6c4'],
    glaze: '#fff1dc',
    foliage: '#c4b58e',
    trunk: '#c0a08a',
    walls: '#fbf2e8',
    roof: '#d9a892',
    shade: '#e2cabd',
    wood: '#caa58d',
    path: '#f7e9dd',
    flowers: ['#eaa7a0', '#f5d79c', '#fdf8f3', '#e0c0cf'],
  },
  /** Pale snowy peaks — "whiter than snow". */
  snow: {
    ink: '#2b3a52',
    glow: '#fdf3e0',
    sun: ['#fdf2d8', '#f5dba4'],
    far: ['#dfe6ef', '#f5f7fa'],
    mid: ['#cfd9e6', '#eef2f7'],
    near: ['#c8d4e0', '#edf1f5'],
    ground: ['#e3e9ef', '#f7f9fb'],
    water: ['#e2ebf2', '#c8d6e4'],
    shimmer: '#ffffff',
    mist: '#f8f8f6',
    cloud: ['#f8f9fb', '#d9e0ea'],
    glaze: '#fffaf0',
    foliage: '#9fb3b6',
    trunk: '#b4a898',
    walls: '#f7f5f1',
    roof: '#bcc4d2',
    shade: '#d4d9e0',
    wood: '#c0b3a3',
    path: '#eef0f0',
    flowers: ['#e4c2cc', '#f1e3b4', '#ffffff', '#d2cde6'],
  },
  /** Gentle amber autumn. */
  autumn: {
    ink: '#52321c',
    glow: '#f9dca6',
    sun: ['#fce8bd', '#f3cf86'],
    far: ['#ead6bf', '#f6ece0'],
    mid: ['#e2c19c', '#f3e3cf'],
    near: ['#d9b088', '#f0dbc4'],
    ground: ['#d7ad87', '#efd9c3'],
    water: ['#e4e4dc', '#c9cfca'],
    shimmer: '#fbf8f0',
    mist: '#faf1e4',
    cloud: ['#fbf4ea', '#ecd8c0'],
    glaze: '#fff1d6',
    foliage: '#e1b27a',
    trunk: '#b29276',
    walls: '#f8efe2',
    roof: '#cf9f82',
    shade: '#dcc4ac',
    wood: '#c4a080',
    path: '#f4e7d4',
    flowers: ['#e8a596', '#f2cf86', '#fdf8f0', '#dcb79f'],
  },
  /** Silvery olive groves of Galilee. */
  olive: {
    ink: '#3a4022',
    glow: '#f8e6bc',
    sun: ['#fcecc4', '#f2d38e'],
    far: ['#dcdcc6', '#f0f0e6'],
    mid: ['#c9cbab', '#e6e8d8'],
    near: ['#b9be98', '#dfe3cf'],
    ground: ['#b9bd97', '#dfe2ce'],
    water: ['#d9e5e2', '#bccfcb'],
    shimmer: '#f8faf6',
    mist: '#f8f4e8',
    cloud: ['#f8f7f0', '#dfdccc'],
    glaze: '#fff4da',
    foliage: '#a9b18a',
    trunk: '#b3a184',
    walls: '#f5f0e2',
    roof: '#cbb291',
    shade: '#d6cfb9',
    wood: '#c1aa88',
    path: '#f1ecdc',
    flowers: ['#e2b0b2', '#efd99a', '#fbf9f2', '#cfc2da'],
  },
  /** Big pale-blue sky over open land. */
  sky: {
    ink: '#22395a',
    glow: '#fdf2da',
    sun: ['#fdefcf', '#f4d699'],
    far: ['#cfdbe8', '#eff3f8'],
    mid: ['#bfd1e3', '#e6edf5'],
    near: ['#b9ccda', '#e3eaf1'],
    ground: ['#c0d0c2', '#e5ece3'],
    water: ['#dbe8f1', '#b7cde0'],
    shimmer: '#fafcfd',
    mist: '#f6f6f2',
    cloud: ['#fafbfc', '#d3dfeb'],
    glaze: '#fff7e6',
    foliage: '#a0b8b0',
    trunk: '#b5a691',
    walls: '#f6f4ef',
    roof: '#bcbccc',
    shade: '#d3d5da',
    wood: '#c0af98',
    path: '#efede5',
    flowers: FLOWERS,
  },
  /** Pale blossom over young green hills. */
  blossom: {
    ink: '#55283a',
    glow: '#fce5c4',
    sun: ['#fdecc8', '#f5d396'],
    far: ['#ecdae0', '#f8eff2'],
    mid: ['#d6dfc4', '#eef2e5'],
    near: ['#c4d6ad', '#e6eedb'],
    ground: ['#bed3a5', '#e3ecd5'],
    water: ['#dfe9ee', '#c2d6df'],
    shimmer: '#fbfcfc',
    mist: '#faf3f0',
    cloud: ['#fbf6f6', '#e8d9df'],
    glaze: '#fff3e2',
    foliage: '#efc3cf',
    trunk: '#bba18f',
    walls: '#fbf5f2',
    roof: '#d6aeb3',
    shade: '#ddcfcf',
    wood: '#c8aa98',
    path: '#f5eee6',
    flowers: ['#eab0c0', '#f4dda2', '#fefbf8', '#d9c4e4'],
  },
  /** Crimson washes deepening to wine — the blood of the Lamb (like the chapel's Hymn 251 deck). */
  crimson: {
    ink: '#4a1520',
    glow: '#fbe3c8',
    sun: ['#fde8cf', '#f3c99c'],
    far: ['#f0d3d3', '#faeeee'],
    mid: ['#e2aeb2', '#f4dcdd'],
    near: ['#d08d95', '#eecbcf'],
    ground: ['#c47b85', '#e9c0c5'],
    water: ['#f0dede', '#dcbfc3'],
    shimmer: '#fdf6f5',
    mist: '#fbf0ee',
    cloud: ['#fbf1f0', '#efd3d4'],
    glaze: '#fff1e6',
    foliage: '#c9a3a0',
    trunk: '#b99088',
    walls: '#fbf3f1',
    roof: '#cf9a9e',
    shade: '#e3c6c7',
    wood: '#c19a92',
    path: '#f6e8e5',
    flowers: ['#e59aa6', '#f2d6a0', '#fdf8f6', '#dcb5c9'],
  },
  /** A green treeline over broad, still blue waters (like the chapel's Hymn 488 deck). */
  waters: {
    ink: '#1d3346',
    glow: '#fbf0d8',
    sun: ['#fcefcf', '#f2d699'],
    far: ['#c6d6c2', '#e8efe4'],
    mid: ['#a5bea2', '#dbe6d6'],
    near: ['#93b090', '#d3e1cf'],
    ground: ['#8fa98c', '#d0dfcc'],
    water: ['#cfdde6', '#9fb6c9'],
    shimmer: '#f7fafb',
    mist: '#f5f5ee',
    cloud: ['#f6f8f8', '#d2dde3'],
    glaze: '#fff6e2',
    foliage: '#87a684',
    trunk: '#ae9f88',
    walls: '#f5f3ec',
    roof: '#b8b0a2',
    shade: '#cfd0c6',
    wood: '#bba88d',
    path: '#eeebe0',
    flowers: FLOWERS,
  },
  /** Open ocean in soft blues. */
  ocean: {
    ink: '#18365a',
    glow: '#fbeccb',
    sun: ['#fdefcc', '#f4d696'],
    far: ['#cfdbea', '#edf2f8'],
    mid: ['#b3c7de', '#e1e9f3'],
    near: ['#a4bcd6', '#dbe5f0'],
    ground: ['#d8d6cc', '#efede6'],
    water: ['#d7e4f0', '#94b0cf'],
    shimmer: '#f8fbfd',
    mist: '#f5f5f2',
    cloud: ['#f8fafc', '#cbd8e8'],
    glaze: '#fff5e0',
    foliage: '#9db3b8',
    trunk: '#b4a692',
    walls: '#f6f4f0',
    roof: '#bcb8c4',
    shade: '#d2d4da',
    wood: '#beae98',
    path: '#efece5',
    flowers: FLOWERS,
  },
  /** Gold and white light breaking through clouds — heaven, glory, His coming. */
  heaven: {
    ink: '#4b3a1c',
    glow: '#fbe6ad',
    sun: ['#fef3d4', '#f6dc9c'],
    far: ['#efe5d0', '#faf6ee'],
    mid: ['#e8dab9', '#f6efe0'],
    near: ['#e2cfa6', '#f3ead6'],
    ground: ['#dfc99c', '#f1e7d1'],
    water: ['#eae6da', '#d3cbb8'],
    shimmer: '#fffdf6',
    mist: '#fdf8ec',
    cloud: ['#fffdf8', '#e6d4ad'],
    glaze: '#fff8e2',
    foliage: '#c3bb92',
    trunk: '#bda783',
    walls: '#fbf6ea',
    roof: '#d9c39c',
    shade: '#e5d9bf',
    wood: '#c9ae86',
    path: '#f7f0e0',
    flowers: ['#ecbfae', '#f4e0a4', '#fffcf6', '#dfcfb3'],
  },
} satisfies Record<string, Palette>;

export type PaletteName = keyof typeof PALETTES;
export const PALETTE_NAMES = Object.keys(PALETTES) as PaletteName[];
